frontend:
  deploymentname: frontend-deployment
  replicas: 1
  image: 562682534333.dkr.ecr.us-east-1.amazonaws.com/frontend-repo:1.0.17
  servicename: frontend-service
  type: LoadBalancer

backend:
  deploymentname: backend-deployment
  replicas: 1
  image: 562682534333.dkr.ecr.us-east-1.amazonaws.com/backend-repo:1.0.17
  servicename: backend-service

db:
  secrets:
    name: db-secrets
    username: c291
    password: UGFzc3dvcmQxMjM=
